### ISSUE TITLE
[无法使用] 1.0.2无法使用

### ISSUE THREAD

**Issue by kejinancheng** [xtaw/LiteLoaderQQNT-Audio-Sender#16]
![image](https://github.com/xtaw/LiteLoaderQQNT-Audio-Sender/assets/108525877/6c16021d-3472-480d-8bd5-be198d0112af)
拖入语音框内无反应

**Comment by xtaw** [comment]
是否有安装ffmpeg

**Comment by Immortal1125** [comment]
安装有ffmpeg无法使用

**Comment by xtaw** [comment]
用chii-devtools看一下控制台有没有报错输出

**Comment by KLuoNuoYa** [comment]
> 用chii-devtools看一下控制台有没有报错输出

​```
 Uncaught ReferenceError: euphonyNative is not defined
    at Friend.sendMessage (local:///D:\Liteload…act/contact.js:31:9)
    at local:///D:\Liteload…c\renderer.js:31:47
```

**Comment by kejinancheng** [comment]
![image](https://github.com/xtaw/LiteLoaderQQNT-Audio-Sender/assets/108525877/01c390f7-c07a-4c2e-80e6-ca3d6aad9cea)
升级到最新版依旧

**Comment by Tianpao512** [comment]
![image](https://github.com/xtaw/LiteLoaderQQNT-Audio-Sender/assets/108525877/10d2bf1d-56c2-43b4-91b1-34faddf6c7ff)
升级到最新版本错误依旧

**Comment by xtaw** [comment]
看起来你并没有安装 **Euphony** 依赖插件？

**Comment by XKaguya** [comment]
遇到了相同的问题
![image](https://github.com/xtaw/LiteLoaderQQNT-Audio-Sender/assets/96401952/c01c83e7-3817-4c8e-9db7-731e7ead7d45)

我的依赖是这样安装的：
![image](https://github.com/xtaw/LiteLoaderQQNT-Audio-Sender/assets/96401952/01a4a3c1-cf3d-47a8-b83f-b55fa136372f)

**Comment by xtaw** [comment]
请认真阅读 Euphony 的 README.md，正确安装依赖

**Comment by xtaw** [comment]
![QQ截图20240502182654](https://github.com/xtaw/LiteLoaderQQNT-Audio-Sender/assets/81631889/48790a95-1033-4823-95a5-45c666b53965)

**Comment by XKaguya** [comment]
> 请认真阅读 Euphony 的 README.md，正确安装依赖

问题解决，感谢大佬的回复
